# Bot configuration
sleep_duration: 3600  # 1 hour in seconds
max_retries: 3
backoff_factor: 2

# Logging
log_file: "autotweet.log"
max_log_size: 5242880  # 5MB
backup_count: 5

# OpenAI
max_tokens: 100
temperature: 0.7
