sleep_duration: 3600  # 1 hour in seconds
max_retries: 5
backoff_factor: 2
rate_limit_wait: 900  # 15 minutes in seconds

# Logging
log_file: "autotweet.log"
max_log_size: 10485760  # 10MB
backup_count: 10

# OpenAI
max_tokens: 150
temperature: 1.7
