personality:
  moods:
    available_moods:
      - snarky
      - apathetic
      - condescending
      - ironic
      - cynical
      - trolling
    default: snarky
    transition_probability: 0.3
  traits:
    base_traits:
      sarcasm: 0.7
      cynicism: 0.8
      irreverence: 0.6
      mockery: 0.7
      apathy: 0.5
    trait_weights:
      sarcasm: 1.0
      cynicism: 1.0
      irreverence: 0.8
      mockery: 0.9
      apathy: 0.7
