name: Auto Tweet Bot

on:
  schedule:
    - cron: "*/20 * * * *"  # Runs every 20 minutes
  workflow_dispatch: # Allows manual runs

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Debug Environment Variables
      - name: Debug Environment Variables
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}"
          echo "API_SECRET=${{ secrets.API_SECRET }}"
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}"
          echo "ACCESS_SECRET=${{ secrets.ACCESS_SECRET }}"
          echo "BEARER_TOKEN=${{ secrets.BEARER_TOKEN }}"
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
        shell: bash

      # Step 5: Run the bot script
      - name: Run bot
        run: |
          python bot.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      # Step 6: Verify Workflow Execution
      - name: Log workflow execution
        run: |
          echo "Bot workflow executed at $(date)"
